num_steps: 5000000
batch_size: 64
lr: 0.0003
memory_size: 300000
gamma: 0.99
multi_step: 1
sigma: 0.2
tau: 0.1
A_lr: 0.01
start_steps: 20000
update_interval: 4
target_update_interval: 8000
use_per: False
dueling_net: False
num_eval_steps: 100000
max_episode_steps: 27000
log_interval: 10
eval_interval: 5000
use_spi: True